# Generated by Django 2.2.4 on 2019-11-19 16:02

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('rate', models.IntegerField(default=0)),
                ('about', models.TextField(max_length=800)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to=products.models.product_directory_path)),
            ],
        ),
    ]
