# Generated by Django 2.2.4 on 2019-11-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191119_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rate_count',
            field=models.IntegerField(default=0),
        ),
    ]
