# Generated by Django 2.2.4 on 2019-12-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191122_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.CharField(blank=True, db_index=True, max_length=20)),
                ('from_us', models.CharField(blank=True, max_length=50)),
                ('from_usnm', models.CharField(blank=True, max_length=50)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('comm_body', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
