# Generated by Django 2.2.4 on 2019-12-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='article',
            new_name='product_name',
        ),
    ]
