# Generated by Django 2.2.4 on 2019-12-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191204_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best',
            field=models.BooleanField(default=False),
        ),
    ]
