# Generated by Django 2.2 on 2019-12-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
